package io.iotos;

import org.openide.util.NbPreferences;

final class OpenItPanel extends javax.swing.JPanel {

    private final OpenItOptionsPanelController controller;

    OpenItPanel(OpenItOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        // TODO listen to changes in form fields and call controller.changed()
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        files = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        files.setColumns(20);
        files.setRows(5);
        jScrollPane1.setViewportView(files);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(OpenItPanel.class, "OpenItPanel.jLabel1.text")); // NOI18N
        add(jLabel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    void load() {
        files.setText(NbPreferences.forModule(OpenItPanel.class).get(FILES, "src/main/resources/application.properties"));
    }
    public static final String FILES = "files";

    void store() {
         NbPreferences.forModule(OpenItPanel.class).put(FILES, files.getText());
    }

    boolean valid() {
        // TODO check whether form is consistent and complete
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea files;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
